### ISSUE TITLE
[Request] Channel order and channel naming

### ISSUE THREAD

**Issue by menesesleonardo** [saleae/logic2-automation#1]
Logic version: Logic2 v2.3.58 MacOS 12.5 Apple Silicon 
API version: logic2_automation-0.0.1-py3

Hi there. It would be great if **channel_order: List[int]** and **channel_names: List[str]** lists were added as final parameters of **LogicDeviceConfiguration**. Currently, channels are sorted in a descending order and first digital then analog, but for industrial automated reporting this feature is crucial. Right now it's possible to add analysers but it's restricted to the ones available (or locally developed), so a naming system would easily solve this.

**Comment by Marcus10110** [comment]
Hi @menesesleonardo,

Thanks for the feedback! So far we're been focusing on the core capture settings, save, and export for data, before we start to consider non-data settings like channel order, channel height, channel labels, viewstate zoom & pan, timing markers, and much more.

You mentioned this:
> but for industrial automated reporting this feature is crucial.

Could you describe how this would be used? Is someone actively watching the software while automation is running to visually validate the results, and they need display to be better organized to make this easy? Or perhaps the exported data isn't organized in an easy to consume way, and changing the channel ordering and labels would improve this? Or are these files being saved, and then loaded later manually, and need channel labels and ordering to make it much easier to understand what the files contain? Or perhaps something else?

One of the big decisions we need to make is weather or not to follow a one-time configuration per capture - i.e. include all data like channel labels, ordering, etc., in the start capture function, or if we should allow these settings to be modified at any time after the capture is complete. 

> Right now it's possible to add analysers but it's restricted to the ones available (or locally developed), so a naming system would easily solve this.

I'm not sure I follow - is this related to the channel ordering and label request? Are you asking for the ability to add analyzers that aren't locally available? If so, where would you like to add them from?

I'd love to get more detail about your use case and make sure we understand what specific problem you're trying to solve, to hopefully help us produce the best possible API.

**Comment by menesesleonardo** [comment]
Hi Marcus, thanks for your reply. Here's a short follow-up on the request. I'll close this issue (since it's not an issue) and move to your forums, which I recently discovered.

> Could you describe how this would be used? Is someone actively watching the software while automation is running to visually validate the results, and they need display to be better organized to make this easy? Or perhaps the exported data isn't organized in an easy to consume way, and changing the channel ordering and labels would improve this? Or are these files being saved, and then loaded later manually, and need channel labels and ordering to make it much easier to understand what the files contain? Or perhaps something else?
> 

We have two scenarios. One is unattended sequence validation, where there's a worker verifying the .sal reports, and there are analog signals depending on digital ones (i.e. i2c controlled DAC), so having each analog signal on top of the digital i2c couple with a protocol analyser will make these reports easier to read.

The second scenario is during QC, where we are actively validating the sequence in real-time. If this is done only on one UUT, it might be easier to do it in Logic's UI, but once the SOP is designed it has to be validated in multiple units, and doing it each time in the UI will add delays.
