### ISSUE TITLE
[Request] Provides an interface to get the ID of the connected device

### ISSUE THREAD

**Issue by RedChinese** [saleae/logic2-automation#18]
Currently, the device ID needs to be manually copied into the code. Can you provide an interface for obtaining the ID of the connected device

**Comment by timreyes** [comment]
@RedChinese This is possible now via the get_devices()[https://saleae.github.io/logic2-automation/automation.html#saleae.automation.Manager.get_devices) command. I hope this was what you were looking for!

**Comment by timreyes** [comment]
Additionally, I wanted to let you know that you can omit the `device_id` argument. In this case, Logic 2 will choose the first real (non-simulated) device.

**Comment by RedChinese** [comment]
Thank you very much for your guidance
