### ISSUE TITLE
Reset Saleae when frozen

### ISSUE THREAD

**Issue by schmiph2** [saleae/logic2-automation#31]
I do automated measurements using the Saleae Logic Pro 8 and the logic2-automation lib. I have an external trigger to start 10 s of analog measurement. It works quite well, but from time to time, the measurement does not stop properly. I don't get the expected results and the LED of the Saleae Logic Pro 8 stays in this cyan-ish color (instead of switching back to green after the measurement). After such an event, I have to unplug the Saleae to reset it and plug it in to use it again. I haven't found a way to connect to it or reset it after it freezes like that via software. It's a bit cumbersome when I want to do measurements over night and after only a couple of measurements, the Saleae freezes like this. 
Is this a known problem? Is there a way to reset the Saleae by software? Would be great to have something like that, so that I could detect the freeze, reset the device and continue my measurements automatically.

**Comment by timreyes** [comment]
@schmiph2 Thank for reporting this issue. We would love to add a method to reset the connection, or provide some kind of way of recovering from something like this.

Can you share more information on what you mean by the below statement? What is your automation script designed to do, and what exactly does the software do when the issue below comes up?

> It works quite well, but from time to time, the measurement does not stop properly.

**Comment by schmiph2** [comment]
Sorry for late feedback, I could not reproduce the issue anymore. Might also be an issue with my code. Maybe reopen it again when it appears again. 

Just for completeness:
I use the software in a headless mode with Xfvb, so, unfortunately, I can't really tell what the software does.
